HAI 1.2
BTW HAII DIS GIVS SUM OF TWO NUMBRS MKAY??
CAN HAS STDIO?
I HAS A x
I HAS A y
I HAS A s
VISIBLE "GIMMEH X"
GIMMEH x
VISIBLE "GIMMEH Y"
GIMMEH y
x IS NOW A NUMBR
y IS NOW A NUMBR
s R SUM OF x AN y
VISIBLE SMOOSH "ITZ " AN s MKAY 
KTHXBYE